version: '2.3'
services:
  elastic:
    image: elasticsearch:7.0.0
    networks: ['network']
    environment: ['discovery.type=single-node', 'logger.level=error']
    healthcheck:
      interval: 5s
      retries: 500
      test: curl localhost:9200
  kosh:
    image: cceh/kosh:feat-elem_id
    command: ['--data_host', 'elastic']
    ports: ['5000:5000']
    networks: ['network']
    healthcheck:
      interval: 5s
      retries: 500
      test: wget -q localhost:5000 2>&1 | grep -q HTTP
    depends_on:
      elastic:
        condition: service_healthy
networks:
  network:
    driver: bridge
